apiVersion: v1
kind: Service
metadata:
  name: go-mockoon-service
  namespace: mockoon
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
  type: NodePort
  selector:
    app: go-mockoon
