apiVersion: v1
kind: Service
metadata:
  name: mockoon-service
  namespace: mockoon
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
  selector:
    app: mockoon
