apiVersion: apps/v1
kind: Pod
metadata:
  name: mockoon-pod
  namespace: mockoon
spec:
  containers:
    - name: mockoon-ctr
      image: mockoon/cli:latest
      args: ["-d", "/data/data.json"]
      ports:
        - containerPort: 3000
      volumeMounts:
        - name: data
          mountPath: "/data"
  volumes:
    - name: data
      configMap:
        name: mockoon-data
  restartPolicy: Always
